config/routes.rb
Rails.application.routes.draw do
  get "team", to:'partner#team'
  get "teachers", to:'partner#teachers'
  resources :courses, :city_areas, :levels, :materials 
  get 'admin/index'
  get 'admin/create'
  get 'admin/dashboard'
  get 'admin/table'
  root to:'home#index'
  
  devise_scope :user do
    get 'profile/edit'    => 'devise/registrations#edit',   :as => :edit_user_registration
    get 'profile/cancel'  => 'devise/registrations#cancel', :as => :cancel_user_registration
  end

  devise_for  :users,
              :path => '',
              :path_names => {  :sign_in =>       'connexion',
                                :sign_out =>      'logout',
                                :sign_up =>       '',
                                :registration =>  'inscription',
                                :edit =>          'edit',
                                 }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

before_action :find_levels
before_action :find_materials

  def index
    @materials = Material.all.order('created_at desc')
    @courses   = Course.all.order('created_at desc')
  end

  

  private
    def find_levels
      @levels = Level.all
    end

    def find_materials
      @materials = Material.all
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/logged/_logged_in.html.erb
<div class="flex-1 flex flex-col overflow-hidden">
  <!-- navbar-->
  <%= render "home/feed/navbar" %>
</div>
<div class="grid md:grid-flow-col ">
  <div class=" md:row-span-2 ">
    <nav class="p-1">
        <%= render "home/feed/sidebar" %> 
    </nav>
  </div>

  <div class="md:row-span-4 mt-8">
    <% @title='Accueil' %>
    <%= render "home/feed/feed" %>
  </div>
  
</div>

app/views/home/logged/_logged_up.html.erb
<%= render "home/shared/styles" %>
<% @title="Accueil" %>
<!-- component -->
<header class="min-h-screen bg-white bg-gradient-to-r from-green-200 to-blue-500 "> 
    <!-- Navigaiton Bar -->
    <nav class="flex items-center py-8 px-4 justify-between">
        <div class="flex items-center">
            <h1 class=" md:hidden text-xl md:text-2xl font-bold text-gray-700 "> LNCLASS</h1>
            <h1 class=" hidden md:block text-xl md:text-2xl font-bold text-gray-700 ">LNCLASS EDUCATION</h1>
        </div>
        <div class="md:flex items-center space-x-3 py-2 px-2 md:px-4 bg-green-500 text-white rounded-lg  transition-all duration-400 transform hover:text-white hover:scale-105 cursor-pointer hover:shadow-lg">
            <%= link_to 'Se Connecter', new_user_session_path, class:"font-semibold " %>    
        </div>
    </nav>
    <!-- End Navigation Bar -->

    <!-- Section Hero -->
    <!-- Box left -->
    <div class="md:flex space-x-16 mt-20 md:mr-0 mr-10">
        <div class="md:flex items-center pl-16 ">
            <div class="">
                <h class="lg:text-5xl  font-bold leading-tight text-3xl">Nous aidons les élèves à obtenir de bonnes notes. </h1>
                <p class="mt-4 text-lg font-normal ">En 2021, 9000 élèves ont obtenuent le BAC avec l'aide de la plateforme LnClass</p>
                <div class="flex mt-10 items-center w-80 space-x-1 py-2 px-1 bg-red-600 text-white rounded-lg transition-all duration-400 transform hover:scale-105 cursor-pointer hover:shadow-lg">
                    <%= link_to "Inscription élève Tle A1, A2 et D", new_user_registration_path, class:"text-xl font-semibold" %>
                    
                </div>
                <%= link_to "Dévenir professeur partenaire", teachers_path, class:"text-xl underline"  %>
            </div>
        </div>
        <!-- Box right -->
        <div class="max-w-lg pr-24 md:flex justify-center items-center  hidden">
            <%= image_pack_tag 'media/images/img-bachelier-2021.jpeg', alt:"image bachelier 2021", class:"rounded-lg" %>
        </div>
    </div>
    <!--Show Brand -->
    <div class="hidden lg:block">
        <ul class="flex mt-32 space-x-36 justify-center">
            <li><a href="#" class="text-2xl font-semibold text-gray-600">Abidjan</a></li>
            <li><a href="#" class="text-2xl font-semibold text-gray-600">Tiassalé</a></li>
            <li><a href="#" class="text-2xl font-semibold text-gray-600">Agboville</a></li>
            <li><a href="#" class="text-2xl font-semibold text-gray-600">Divo</a></li>
            <li><a href="#" class="text-2xl font-semibold text-gray-600">Man</a></li>
            <li><a href="#" class="text-2xl font-semibold text-gray-600">Bouaké</a></li>
        </ul>
    </div>
</header>