config/routes.rb
Rails.application.routes.draw do
  get "team", to:'partner#team'
  get "teachers", to:'partner#teachers'
  resources :courses, :city_areas, :levels, :materials 
  get 'admin/index'
  get 'admin/create'
  get 'admin/dashboard'
  get 'admin/table'
  root to:'home#index'
  
  devise_scope :user do
    get 'profile/edit'    => 'devise/registrations#edit',   :as => :edit_user_registration
    get 'profile/cancel'  => 'devise/registrations#cancel', :as => :cancel_user_registration
  end

  devise_for  :users,
              :path => '',
              :path_names => {  :sign_in =>       'connexion',
                                :sign_out =>      'logout',
                                :sign_up =>       '',
                                :registration =>  'inscription',
                                :edit =>          'edit',
                                 }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :user

  validates :title,
            :user_id,
            :slug, presence: true
 
  #SLUG
  extend FriendlyId
    friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_material, only: %i[ show edit update destroy ]

  # GET /materials or /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1 or /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials or /materials.json
  def create
    @material = current_user.materials.build(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: "Material was successfully created." }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1 or /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: "Material was successfully updated." }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1 or /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: "Material was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def material_params
      params.require(:material).permit(:title, :slug, :user_id)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_with(model: material) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
        <% material.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  
  <div class="actions mt-2">
    <%= form.submit "Add Material", class:"bg-blue-400 p-2 border-2 border-rounded-md font-bold" %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form', material: @material %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Materials</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.title %></td>
        <td><%= material.slug %></td>
        <td><%= material.user_id %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path, class:"bg-blue-400 border-2 border-rounded-lg p-2 font-bold " %>

</div>

app/views/materials/new.html.erb
<div class="container">
<h1>New Material</h1>

<%= render 'form', material: @material %>
</div>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @material.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @material.slug %>
</p>

<p>
  <strong>User:</strong>
  <%= @material.user_id %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>